In [17]:
import numpy as np
import pandas as pd
import random as rnd

rnd.seed(42)

In [2]:
class Maze:
    matrix = np.array
    connectivity = None

    def __init__(self, path):
        with open(path, 'r') as maze:
            maze = [int(x) for x in maze.readline().split()]
        width, height = maze[0:2]
        connectivity = maze[2]
        maze = maze[3:]
        matrix = []

        for y in range(height):
            matrix.append(maze[0+height*y: width + height*y])

        self.matrix = np.array(matrix)
        self.connectivity = connectivity


    def up_frame(self, cell_code: int):
        return cell_code//1%2==1

    def right_frame(self, cell_code: int):
        return cell_code//2%2==1

    def bottom_frame(self, cell_code: int):
        return cell_code//4%2==1

    def left_frame(self, cell_code: int):
        return cell_code//8%2==1


    def up_frame_coords(self, x: int, y: int):
        cell_code = self.matrix[y][x]
        return cell_code//1%2==1

    def right_frame_coords(self, x: int, y: int):
        cell_code = self.matrix[y][x]
        return cell_code//2%2==1

    def bottom_frame_coords(self, x: int, y: int):
        cell_code = self.matrix[y][x]
        return cell_code//4%2==1

    def left_frame_coords(self, x: int, y: int):
        cell_code = self.matrix[y][x]
        return cell_code//8%2==1

In [ ]:
class Ant:
    import numpy as np

    route = []
    def __init__(self, x:int, y:int):
        self.x, self.y = x, y
        self.position = (x, y)

In [35]:
class ACO:
    import numpy as np

    stopping_criteria = str
    graph = np.ndarray
    ant_num = int
    ant_locations = None
    evaporation_rate = float
    maze = np.ndarray
    target_position = (int, int)

    iter_counter = 0
    iter_stop = int

    def __init__(self, width:int, height:int, maze:np.ndarray = None, graph:np.ndarray = None, edge_graph:np.ndarray = None,
                 ant_num:int = None, evaporation_rate:float = 0.1, stopping_criteria:str = "iterations", iter_stop:int = 100):
        self.width, self.height = width, height
        self.evaporation_rate = evaporation_rate
        self.stopping_criteria = stopping_criteria
        self.iter_stop = iter_stop


        if (maze != None and graph != None) or (maze != None and edge_graph != None) or (edge_graph != None and graph != None):
            raise Exception("Value Error: two or more not None graph representations provided")

        if graph != None:
            self.graph = graph
        elif edge_graph != None:
            self.graph = self.edge2ord(edge_graph)
        elif maze != None:
            self.graph = self.maze2ord(maze)

        else:
            raise Exception("Value Error: provided None maze representations")





        if ant_num is None:
            self.ant_num = self.graph.shape[0]*self.graph.shape[0][1]
        else:
            self.ant_num = ant_num


    def iterations_criterion_check(self) -> bool:
        return self.iter_counter >= self.iter_stop


    def get_shortest_edge(self, edge_graph):
        pass
    def get_shortest(self, graph):
        pass
    def edge2ord(self, edge_graph):
        pass
    def ord2edge(self, graph):
        pass
    def maze2ord(self, maze):
        size = maze.shape[0]*maze.shape[1]
        graph = [[0]*size]*size

        for i in range(size):
            for j in range(size):
                pass

    def move(self):
        return 1, 2

    def train(self, maze:np.ndarray):
        ant_positions = rnd.sample([(x, y) for x in range(maze.shape[0]) for y in range(maze.shape[1])], k=self.ant_num)
        ants = [Ant(pos[0], pos[1]) for pos in ant_positions]

        stopping_criteria = callable
        if self.stopping_criteria == "iterations":
            stopping_criteria = self.iterations_criterion_check

        while not stopping_criteria():
            for ant in ants:
                while ant.position !=
            self.iter_counter+=1

SyntaxError: expected ':' (4127121870.py, line 73)

In [4]:
def up_frame(cell_code: int):
    return cell_code//1%2==1

def right_frame(cell_code: int):
    return cell_code//2%2==1

def bottom_frame(cell_code: int):
    return cell_code//4%2==1

def left_frame(cell_code: int):
    return cell_code//8%2==1


def load_maze(path: str):
    with open(path, 'r') as maze:
        maze = [int(x) for x in maze.readline().split()]
    width, height = maze[0:2]
    connectivity = maze[2]
    maze = maze[3:]
    matrix = []

    for y in range(height):
        matrix.append(maze[0+height*y: width + height*y])

    return matrix, connectivity

In [5]:
matrix_func, c = load_maze("mazes/M100_1.mz")
np.array(matrix_func)

array([[13,  1,  5,  3,  9,  5,  1,  7,  9,  5,  7, 13,  5,  3, 11],
       [ 9,  6,  9,  4,  0,  7, 12,  3,  8,  5,  7, 11, 11,  8,  6],
       [12,  3, 14,  9,  6,  9,  5,  4,  4,  7, 13,  4,  4,  0,  3],
       [ 9,  4,  7, 14, 13,  0,  5,  5,  1,  7,  9,  3, 13,  6, 10],
       [12,  5,  1,  7, 13,  4,  7,  9,  4,  3, 10, 12,  5,  5,  2],
       [ 9,  7, 14, 13,  5,  3,  9,  2, 13,  4,  6,  9,  5,  5,  6],
       [12,  5,  3, 29,  3, 10, 14, 14, 11,  9,  5,  6, 13,  1,  3],
       [ 9,  5,  0,  5,  0,  4,  1,  5,  4,  6, 11,  9,  5,  6, 10],
       [14, 13,  6, 11,  8,  7, 10, 11, 13,  1,  4,  4,  7,  9,  2],
       [13,  5,  1,  2, 12,  7,  8,  2, 13,  2,  9,  3, 11, 14, 10],
       [11,  9,  6,  8,  7,  9,  6, 12,  7, 12,  2, 14, 12,  5,  6],
       [ 8,  4,  3, 14, 13,  2, 13,  3, 13,  1,  6, 13,  1,  5,  3],
       [10, 11, 12,  5,  5,  0,  1,  4,  3,  8,  3, 13,  4,  3, 10],
       [ 8,  4,  5,  3,  9,  2, 12,  3, 14, 14, 12,  5,  5,  6, 10],
       [12,  7, 13,  6, 14, 12,  7

In [6]:
matrix_func[0][1]

1

In [7]:
M = Maze("mazes/M100_1.mz")
type(M.matrix)

numpy.ndarray

In [8]:
bottom_frame(5)

True

In [9]:
np.equal(M.matrix, matrix_func)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  T

In [20]:
a = rnd.sample([(x, y) for x in range(M.matrix.shape[0]) for y in range(M.matrix.shape[1])], k=M.matrix.shape[1]*M.matrix.shape[0])

In [32]:
np.unique(a, axis=1)

array([[ 1,  3],
       [12,  1],
       [10, 11],
       [ 1,  0],
       [ 3, 13],
       [ 1,  2],
       [ 0,  8],
       [ 5,  9],
       [14, 14],
       [ 8, 11],
       [ 4,  0],
       [ 4, 11],
       [11,  6],
       [ 8,  4],
       [ 3,  9],
       [ 9,  3],
       [ 2,  3],
       [12,  5],
       [ 9, 11],
       [ 9, 12],
       [ 8,  1],
       [ 4,  2],
       [13,  5],
       [13,  9],
       [ 6, 14],
       [ 3,  3],
       [ 1,  9],
       [13,  3],
       [11,  3],
       [ 7,  5],
       [ 6,  0],
       [ 7,  3],
       [ 7,  0],
       [ 7, 14],
       [12,  6],
       [ 0, 13],
       [11,  7],
       [11,  2],
       [11,  0],
       [ 1, 10],
       [14, 11],
       [ 6, 13],
       [ 5, 11],
       [ 1, 12],
       [ 4,  3],
       [ 3,  4],
       [13,  4],
       [ 9,  2],
       [ 7,  9],
       [ 2,  5],
       [12, 13],
       [ 3,  1],
       [14,  3],
       [ 7, 13],
       [12,  0],
       [ 1,  4],
       [ 7,  8],
       [ 9,  5],
       [13, 12

In [37]:
M.left_frame_coords(0, 0)

True

In [38]:
M.matrix

array([[13,  1,  5,  3,  9,  5,  1,  7,  9,  5,  7, 13,  5,  3, 11],
       [ 9,  6,  9,  4,  0,  7, 12,  3,  8,  5,  7, 11, 11,  8,  6],
       [12,  3, 14,  9,  6,  9,  5,  4,  4,  7, 13,  4,  4,  0,  3],
       [ 9,  4,  7, 14, 13,  0,  5,  5,  1,  7,  9,  3, 13,  6, 10],
       [12,  5,  1,  7, 13,  4,  7,  9,  4,  3, 10, 12,  5,  5,  2],
       [ 9,  7, 14, 13,  5,  3,  9,  2, 13,  4,  6,  9,  5,  5,  6],
       [12,  5,  3, 29,  3, 10, 14, 14, 11,  9,  5,  6, 13,  1,  3],
       [ 9,  5,  0,  5,  0,  4,  1,  5,  4,  6, 11,  9,  5,  6, 10],
       [14, 13,  6, 11,  8,  7, 10, 11, 13,  1,  4,  4,  7,  9,  2],
       [13,  5,  1,  2, 12,  7,  8,  2, 13,  2,  9,  3, 11, 14, 10],
       [11,  9,  6,  8,  7,  9,  6, 12,  7, 12,  2, 14, 12,  5,  6],
       [ 8,  4,  3, 14, 13,  2, 13,  3, 13,  1,  6, 13,  1,  5,  3],
       [10, 11, 12,  5,  5,  0,  1,  4,  3,  8,  3, 13,  4,  3, 10],
       [ 8,  4,  5,  3,  9,  2, 12,  3, 14, 14, 12,  5,  5,  6, 10],
       [12,  7, 13,  6, 14, 12,  7

In [42]:
np.argmax(M.matrix)//15

6

In [48]:
np.unravel_index(np.argmax(M.matrix, axis=None), M.matrix.shape)[::-1]

(3, 6)

In [50]:
M.matrix[6][3]

29